---
title: "Supplemental info about phylodiversity in evolutionary computation"
author: "Jose Guadalupe Hernandez, Alexander Lalejini, Emily Dolson"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: ["book.bib", "packages.bib"]
biblio-style: apalike
nocite: '@*'
link-citations: yes
github-repo: emilydolson/phylodiversity-metrics-in-EC-GPTP-2021
description: "Supplemental info for 'What can phylogenetic metrics tell us about useful diversity in evolutionary algorithms?'"
---

# Introduction

This is the supplemental material for our work, ['What can phylogenetic metrics tell us about useful diversity in evolutionary algorithms?'](https://arxiv.org/abs/2108.12586).
This is not intended as a stand-alone document, but as a companion to our paper.

## About our supplemental material

As you may have noticed (unless you're reading a pdf version of this), our supplemental material is hosted using [GitHub pages](https://pages.github.com/).
We compiled our data analyses and supplemental documentation into this nifty web-accessible book using [bookdown](https://bookdown.org).

The source code/configuration files for this supplemental material and all experiments in the paper can be found in [this GitHub repository](https://github.com/emilydolson/phylodiversity-metrics-in-EC-GPTP-2021).

Our supplemental material includes the following:

TODO

## Contributing authors

- [Jose Guadalupe Hernandez](https://jgh9094.github.io/)
- [Alexander Lalejini](https://lalejini.com/)
- [Emily Dolson](http://emilyldolson.com/)

## Research overview

### Abstract

> **It is generally accepted that "diversity" is associated with success in evolutionary algorithms. However, diversity is a broad concept that can be measured and defined in a multitude of ways. To date, most evolutionary computation research has measured diversity using the richness and/or evenness of a particular genotypic or phenotypic property. While these metrics are informative, we hypothesize that other diversity metrics are more strongly predictive of success. Phylogenetic diversity metrics are a class of metrics popularly used in biology, which take into account the evolutionary history of a population. Here, we investigate the extent to which 1) these metrics provide different information than those traditionally used in evolutionary computation, and 2) these metrics better predict the long-term success of a run of evolutionary computation. We find that, in most cases, phylogenetic metrics behave meaningfully differently from other diversity metrics. Moreover, our results suggest that phylogenetic diversity is indeed a better predictor of success.

