name: Build and deploy to GitHub Pages
on:
  push:
    branches:
      - none

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/checkout@v2
      - name: Cache Book
        id: cache-book
        uses: actions/cache@v2
        with:
          path: |
            _bookdown_files
            phylodiversity-in-EC-supplement_cache
            phylodiversity-in-EC-supplement_files
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BRANCH: master # The branch the action should deploy to
          FOLDER: _book # The folder the action should deploy
          CLEAN: true # Automatically remove deleted files from the deploy branch
